<a href="https://colab.research.google.com/github/melissa-mariano/projects/blob/main/TP1_LES_DIFFERENTS_MODES_DE_VARIABLES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **I. VARIABLES NUMERIQUES ET CHAINES DE CARACTERES**

In [1]:
#### Exercice 1 ####
x = log(2)
x
exp(x) # c'est exact

# diff entre paste et paste0:
# paste() met un espace
# paste0() colle direct
paste("Data", "Scientist")
paste0("Data", "Scientist")

phrase <- "Je veux être un data scientist."
toupper(phrase)
nchar(phrase)
cat("le nombre de caractères de cette phrase est", nchar(phrase))

ls() # voir tout
rm(x) # on efface x

[1] 0.6931472

[1] 2

[1] "Data Scientist"

[1] "DataScientist"

[1] "JE VEUX ÊTRE UN DATA SCIENTIST."

[1] 31

le nombre de caractères de cette phrase est 31

[1] "phrase" "x"

# **II. VECTEURS**

In [2]:
#### Exercice 2 ####
v1 <- 1:12
v1 <- c(v1, 16, 17, 18) # rajout à la fin

#### Exercice 3 ####
v2 = seq(0, 5, by=0.5)
v2_alt <- seq(0, 5, length=11) # autre facon

#### Exercice 4 ####
v3 <- seq(2, 100, 2) # nombres pairs
length(v3)

v4 = rep(0:9, each=3)
length(v4)
rm(v4)

#### Exercice 5 ####
v5 <- paste0("individu", 1:100)

#### Exercice 6 ####
v3[1] # premier
v3[length(v3)] # dernier
v3[8:20] # de 8 a 20
v3[c(8, 10, 20)] # indices precis

v3 < 10 # ca donne des TRUE/FALSE, c'est du LOGIQUE
v3[v3 < 10] # filtre les petits

v3[v3 >= 20]
v3[v3 > 10 & v3 < 20]

which(v3 > 10 & v3 < 20) # trouve les places

v3[1] <- "a"
v3
# Explication: le vecteur devient 'character' (texte) partout
# on peut pas mélanger types dans un vecteur

#### Exercice 7 ####
vec1 <- c(1,2,3)
vec2 <- c(4,5,6)
vec1 + vec2

# recyclage:
short <- c(1,2)
vec1 + short # message d'alerte car pas meme taille
# R recommence le petit vecteur au debut

#### Exercice 8 ####
x = c(3, NA, 6)
is.na(x)
summary(x)
mean(x) # donne NA
mean(x, na.rm=T) # ignore le vide

data(precip)
names(precip)
precip[c("Philadelphia", "Columbia", "Baltimore", "Sacramento")]
precip[precip < 30]

#### Exercice 9 ####
x <- 152:175
v20 <- rep(c(6,7,2,3), 5)
valeurs <- c(rep(2,6), rep(7,8), rep(4,10))
mean(valeurs)

#### Exercice 10 ####
# poids <- scan() # a faire a la main
poids = c(47, 56, 64, NA, 75, 51, 72, 95, 63, 79)
mean(poids, na.rm=T)
median(poids, na.rm=T)
poids[poids > mean(poids, na.rm=T)]

[1] 50

[1] 30

[1] 2

[1] 100

 [1] 16 18 20 22 24 26 28 30 32 34 36 38 40

[1] 16 20 40

 [1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[49] FALSE FALSE

[1] 2 4 6 8

 [1]  20  22  24  26  28  30  32  34  36  38  40  42  44  46  48  50  52  54  56
[20]  58  60  62  64  66  68  70  72  74  76  78  80  82  84  86  88  90  92  94
[39]  96  98 100

[1] 12 14 16 18

[1] 6 7 8 9

 [1] "a"   "4"   "6"   "8"   "10"  "12"  "14"  "16"  "18"  "20"  "22"  "24"
[13] "26"  "28"  "30"  "32"  "34"  "36"  "38"  "40"  "42"  "44"  "46"  "48"
[25] "50"  "52"  "54"  "56"  "58"  "60"  "62"  "64"  "66"  "68"  "70"  "72"
[37] "74"  "76"  "78"  "80"  "82"  "84"  "86"  "88"  "90"  "92"  "94"  "96"
[49] "98"  "100"

[1] 5 7 9

Warning message in vec1 + short:
“longer object length is not a multiple of shorter object length”

[1] 2 4 4

[1] FALSE  TRUE FALSE

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
   3.00    3.75    4.50    4.50    5.25    6.00       1

[1] NA

[1] 4.5

 [1] "Mobile"              "Juneau"              "Phoenix"
 [4] "Little Rock"         "Los Angeles"         "Sacramento"
 [7] "San Francisco"       "Denver"              "Hartford"
[10] "Wilmington"          "Washington"          "Jacksonville"
[13] "Miami"               "Atlanta"             "Honolulu"
[16] "Boise"               "Chicago"             "Peoria"
[19] "Indianapolis"        "Des Moines"          "Wichita"
[22] "Louisville"          "New Orleans"         "Portland"
[25] "Baltimore"           "Boston"              "Detroit"
[28] "Sault Ste. Marie"    "Duluth"              "Minneapolis/St Paul"
[31] "Jackson"             "Kansas City"         "St Louis"
[34] "Great Falls"         "Omaha"               "Reno"
[37] "Concord"             "Atlantic City"       "Albuquerque"
[40] "Albany"              "Buffalo"             "New York"
[43] "Charlotte"           "Raleigh"             "Bismark"
[46] "Cincinnati"          "Cleveland"           "Columbus"
[49] "Oklahoma City"       "Portland"            "Philadelphia"
[52] "Pittsburg"           "Providence"          "Columbia"
[55] "Sioux Falls"         "Memphis"             "Nashville"
[58] "Dallas"              "El Paso"             "Houston"
[61] "Salt Lake City"      "Burlington"          "Norfolk"
[64] "Richmond"            "Seattle Tacoma"      "Spokane"
[67] "Charleston"          "Milwaukee"           "Cheyenne"
[70] "San Juan"

Philadelphia     Columbia    Baltimore   Sacramento
        39.9         46.4         41.8         17.2

            Phoenix         Los Angeles          Sacramento       San Francisco
                7.0                14.0                17.2                20.7
             Denver            Honolulu               Boise Minneapolis/St Paul
               13.0                22.9                11.5                25.9
        Great Falls                Reno         Albuquerque             Bismark
               15.0                 7.2                 7.8                16.2
        Sioux Falls             El Paso      Salt Lake City             Spokane
               24.7                 7.8                15.2                17.4
          Milwaukee            Cheyenne
               29.1                14.6

[1] 4.5

[1] 66.88889

[1] 64

[1] NA 75 72 95 79

# **III. MATRICES**

In [3]:
#### Exercice 11 ####
Mat <- matrix(1:12, nrow=4, byrow=T)
Mat[3,2]
Mat[3,]

v_ex = Mat[2, c(1,3)]
class(v_ex) # c'est un vecteur numeric

Mat[4, 3] = 20
Mat[, 2] <- 1:4
Mat <- cbind(Mat, 13:16)
Mat <- rbind(Mat, 33:36)
Mat <- Mat[, -3] # supprime la 3eme col

#### Exercice 12 ####
id = diag(10)
randomMat = matrix(rnorm(100, 0, 5), 10, 10)
# produit matriciel:
id %*% randomMat # ca change rien (element neutre)

[1] 8

[1] 7 8 9

[1] "integer"

      [,1]      [,2]      [,3]      [,4]       [,5]       [,6]       [,7]
 [1,] -2.586137  4.106092  2.486659 -7.4704187  1.0808619  4.1636337 -0.2753898
 [2,] -1.708912 -2.084962  2.153689 -1.6702261  2.1980217  0.9087350  1.9882920
 [3,] -1.167786 -2.312416  2.014544 -3.0179641 -4.2873681  0.7457840 -6.0472802
 [4,]  0.464947  7.130294 -5.686370  1.0055514  0.1566309  2.1089489  4.7968615
 [5,]  2.583393  5.985683 -4.619793  3.4265252 -3.5033006 -9.9636954  6.0953334
 [6,]  3.236721  6.862312  7.710941 -1.3044217 12.5314186  0.5623731  5.2071583
 [7,] 16.143845 -6.894165  1.927817  0.2408691  2.0937441  1.2087456 -4.6095053
 [8,]  2.880584 -7.387222  3.609217 10.0258018  0.4124375  2.4931315 -1.2094858
 [9,] -5.370209 -6.341830  1.075243  1.7757516  9.1587257  1.7512579 -6.2598377
[10,]  7.645062 -1.004049  2.300263  6.1040286  5.0595277 -4.4913844 10.9250466
      [,8]        [,9]         [,10]
 [1,]  -8.4527803  -0.93894636  4.3657144
 [2,]  -0.9895835   0.05332354 -7.1160463
 [3,]  -0.8771862  -1.62499819  0.6346587
 [4,]   1.5445131 -16.29318969 -2.2900548
 [5,]  -3.7387671   2.73161684 -9.4380953
 [6,]   1.6168105  -7.01443651  2.4204672
 [7,]   5.0513160  -1.03031865 -3.4949326
 [8,]   4.8952969   3.12479412 -3.8275399
 [9,]   1.6553588  -2.30420210 -3.4044028
[10,] -10.7002670  -9.19323919  2.9462834

# **IV. LISTES**

In [4]:
#### Exercice 14 ####
L = list("M", 54, c(360, 480, 600, -700))
L[[3]][4] # cherche le -700

names(L) <- c("sexe", "age", "soldes")
L$age
L[["soldes"]][4]

#### Exercice 15 ####
p <- c(Fax=10, Dux=20, Axe=30)
pp <- c(Fax=3, Dux=5, Axe=8)
T1 = rbind(p, pp)
rownames(T1) <- c("pellicules", "papier photo")

# trimestre 2
T2 = matrix(c(15, 15, 20, 5, 5, 10), 2, 3, byrow=T)
colnames(T2) = c("Fax", "Dux", "Axe")
rownames(T2) = c("pellicules", "papier photo")

Total = T1 + T2
Total

[1] -700

[1] 54

[1] -700

             Fax Dux Axe
pellicules   25  35  50
papier photo  8  10  18